In [1]:
import numpy as np

In [10]:
mylist = [1, 2, 3, 5]
array = np.array(mylist)
array

array([1, 2, 3, 5])

In [4]:
array.shape

(4,)

In [5]:
np.array(mylist*3)

array([1, 2, 3, 5, 1, 2, 3, 5, 1, 2, 3, 5])

In [6]:
np.repeat(mylist, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 5, 5, 5])

In [8]:
print(np.arange(0, 10, 2))
print(np.linspace(0, 10, 5))

[0 2 4 6 8]
[ 0.   2.5  5.   7.5 10. ]


In [9]:
np.random.random((2,3))

array([[0.99198703, 0.80307476, 0.8916625 ],
       [0.93863679, 0.29298818, 0.21887742]])

In [13]:
np.ones((3,3), int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [16]:
np.zeros((2,1))

array([[0.],
       [0.]])

In [17]:
a1 = np.array([1,2])

a2 = np.array([[0,0],
               [1,1]])

a3 = np.array([[1, 2],
               [1, 2]])

In [21]:
a2+a3

array([[1, 2],
       [2, 3]])

In [20]:
a2+a1

array([[1, 2],
       [2, 3]])

In [26]:
y = np.array([1,2,3], dtype=float) # int8, int32, int64, boolean, float
y.dtype

dtype('float64')

In [27]:
y

array([1., 2., 3.])

In [28]:
x = np.array([2,4,6])
y = np.array([2])

In [29]:
print(x/y)
print(x*y)
print(x-y)
print(x+y)

[1. 2. 3.]
[ 4  8 12]
[0 2 4]
[4 6 8]


In [35]:
y = y.reshape((1,1))
x = x.reshape((3,1))

In [37]:
x

array([[2],
       [4],
       [6]])

In [34]:
x.dot(y)

array([[ 4],
       [ 8],
       [12]])

In [39]:
print(x.shape)
print(x.T.shape)
x.T

(3, 1)
(1, 3)


array([[2, 4, 6]])

In [40]:
z = np.array([1], dtype=int)

In [42]:
z.dtype

dtype('int64')

In [45]:
z = z.astype('float')
z.dtype

dtype('float64')

In [46]:
x[0:2]

array([[2],
       [4]])

In [75]:
x = np. arange(36)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [76]:
x = x.reshape((4,9))
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [77]:
x.resize((6, 6))
x

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [78]:
x[2:4,3:]

array([[15, 16, 17],
       [21, 22, 23]])

In [79]:
x > 2

array([[False, False, False,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [80]:
x[x>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35])

In [81]:
# copare copy() and non copy

In [82]:
x1 = x[2:4,3:]
x1

array([[15, 16, 17],
       [21, 22, 23]])

In [83]:
x1[1,1] = 10
x1

array([[15, 16, 17],
       [21, 10, 23]])

In [84]:
x

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 10, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [86]:
x2 = x.copy()
x2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 10, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [87]:
x2[:, 1] = 0
x2

array([[ 0,  0,  2,  3,  4,  5],
       [ 6,  0,  8,  9, 10, 11],
       [12,  0, 14, 15, 16, 17],
       [18,  0, 20, 21, 10, 23],
       [24,  0, 26, 27, 28, 29],
       [30,  0, 32, 33, 34, 35]])

In [88]:
x

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 10, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [90]:
np.savetxt('test.txt', x, delimiter=',')